### ISSUE TITLE
freepascal comments // confuse the syntax highlighting in the line that follows

### ISSUE THREAD

**Issue by stefc** [fnkr/ST-Pascal#2]
I use your plugin as a IDE for freepascal developing. 

In Freepascal you can use also  // as comment 

you support this that's ok, but the line that follows don't have any syntax highlighting. 

For example : 

this don't work on the second line : 
```
//  THexagon = array[0..5] of TPoint;
function Point(x,y: Integer): TPoint;
```

this work, the space line that follows reset's the syntax highlighting state I think: 
```
//  THexagon = array[0..5] of TPoint;

function Point(x,y: Integer): TPoint; 
```

**Comment by fnkr** [comment]
I do not longer use SublimeText so I dont update this anymore but if you send me a pull request I will merge it.

**Comment by 101100** [comment]
I manually added your `Pascal.tmLangauage` to `Pascal Snippets.sublime-package` and that fixed this issue.  Can you update your ST3 package to include `Pascal.tmLangauage`?

**Comment by inouetoukyou** [comment]
In Sublime Text 3, there is no such problem. Maybe it's fixed...

**Comment by fnkr** [comment]
Cannot reproduce.

![image](https://user-images.githubusercontent.com/616991/39075113-6b317ac0-44f4-11e8-84e9-7e022e7c7754.png)
