### ISSUE TITLE
Syntax highlighting doesn't work on MacOSX

### ISSUE THREAD

**Issue by chrilith** [fnkr/ST-Pascal#3]
Hi,

If the file extension is upper case, the syntax remain unchanged in the editor.
Changing file name to lower case do the trick but it is not the solution :).

Found on MacOSX, works great on Windows.

Thanks!

**Comment by fnkr** [comment]
I do not longer use SublimeText so I dont update this anymore however if you send me a pull request I will merge it.

**Comment by chrilith** [comment]
Well, this problem seems to impact all highlighters on Mac. Not your issue then :)
